// Seed for skills
db.skills.drop();
var s = ['Communication', 'Team Work', 'Customer Service', 'Project Leadership'];
s.forEach(function(name){
  db.skills.save({name: name});
});

// Seed for roles
db.roles.drop();
var r = ['Office Assistant', 'Web Developer', 'Events volunteer'];
r.forEach(function(name){
  db.roles.save({name: name});
});

// Seed for nonprofits
// db.nonprofits.drop();
// var n = ['Habitat for Humanity', 'British Red Cross', 'ABL Health', 'Other'];
// n.forEach(function(name){
//   db.nonprofits.save({name: name});
// });

// Seeds for universities
db.universities.drop();
var u = [
"Anglia Ruskin University"
"Arts University Bournemouth"
"University of the Arts London"
"Aston University"
"University of Bath"
"Bath Spa University"
"University of Bedfordshire"
"University of Birmingham"
"Birmingham City University"
"University College Birmingham"
"Bishop Grosseteste University"
"University of Bolton"
"Bournemouth University"
"BPP University"
"University of Bradford"
"University of Brighton"
"University of Bristol"
"Brunel University"
"University of Buckingham"
"Buckinghamshire New University"
"University of Cambridge"
"Canterbury Christ Church University"
"University of Central Lancashire"
"University of Chester"
"University of Chichester"
"City University London"
"Coventry University"
"Coventry University, London"
"Cranfield University"
"University for the Creative Arts"
"University of Cumbria"
"De Montfort University"
"University of Derby"
"Durham University"
"University of East Anglia"
"University of East London"
"Edge Hill University"
"University of Essex"
"University of Exeter"
"Falmouth University"
"University of Gloucestershire"
"University of Greenwich"
"Harper Adams University"
"University of Hertfordshire"
"University of Huddersfield"
"University of Hull"
"Imperial College London"
"Keele University"
"University of Kent"
"Kingston University"
"Lancaster University"
"University of Leeds"
"Leeds Metropolitan University"
"Leeds Trinity University"
"University of Leicester"
"University of Lincoln"
"University of Liverpool"
"Liverpool Hope University"
"Liverpool John Moores University"
"University of London"
"Birkbeck, University of London"
"Courtauld Institute of Art"
"Goldsmiths, University of London"
"Heythrop College"
"Institute of Cancer Research"
"King's College London"
"London Business School"
"London School of Economics"
"London School of Hygiene & Tropical Medicine"
"Queen Mary, University of London"
"Royal Northern College of Music"
"Royal Academy of Music"
"Royal Holloway, University of London"
"Royal Veterinary College"
"St George's, University of London"
"School of Advanced Study"
"School of Oriental and African Studies"
"School of Pharmacy, University of London"
"University College London"
"London Metropolitan University"
"London South Bank University"
"Loughborough University"
"University of Manchester"
"Manchester Metropolitan University"
"Middlesex University"
"Newcastle University"
"Newman University"
"University of Northampton"
"Northumbria University"
"Norwich University of the Arts"
"University of Nottingham"
"Nottingham Trent University"
"Open University"
"University of Oxford"
"Oxford Brookes University"
"University of Plymouth"
"University of Portsmouth"
"University of Reading"
"Richmond University"
"Roehampton University"
"Royal Agricultural University"
"University of Salford"
"University of Sheffield"
"Sheffield Hallam University"
"University of Southampton"
"Southampton Solent University"
"University of St Mark & St John"
"St. Mary's University College"
"Staffordshire University"
"University of Sunderland"
"University of Surrey"
"University of Sussex"
"Teesside University"
"Thames Valley University"
"University of Warwick"
"University of Westminster"
"University of the West of England"
"University of Winchester"
"University of Wolverhampton"
"University of Worcester"
"University of York"
"York St John University"
];
u.forEach(function(name){
  db.universities.save({name: name});
});
